package com.mpriester.resumerestapi.ResumeRestApi;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

/**
 * Root resource (exposed at "myresource" path)
 */
@Path("myresource")
public class MyResource {

    /**
     * Method handling HTTP GET requests. The returned object will be sent
     * to the client as "text/html" media type and render as a web page.
     *
     * @return String that will be returned as a text/html response.
     */
    @GET
    @Produces(MediaType.TEXT_HTML)
    public String getIt() {
    	String content;
    	content = "<html><head><title>Marquita Priester's Resume</title>"
    			+"<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css' integrity='sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb' crossorigin='anonymous'>"
    			+"<link href='https://fonts.googleapis.com/css?family=Monsieur La Doulaise' rel='stylesheet'>"
    			+"<script src='https://code.jquery.com/jquery-3.2.1.slim.min.js' integrity='sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN' crossorigin='anonymous'></script>"
    			+"<script src='https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js' integrity='sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh' crossorigin='anonymous'></script>"
    			+"<script src='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js' integrity='sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ' crossorigin='anonymous'></script>"
    			+"</head>"
    			+"<body><div class='row' style='padding: 1%;'><div class='col-md-12'><h1 style='font-family: Monsieur La Doulaise; text-align: center;'>Marquita Priester</h1></div>"
    			+"<div class='col-md-12' style='text-align: center;'><p> 715 N Church St unit 309<br />"
    			+"Charlotte, NC 28202<br />"
    			+"(704) 493-0000<br />"
    			+"Email:mbpriester@gmail.com<br />"
    			+"LinkedIN: <a href='https://www.linkedin.com/in/marquita-priester-8b775217/'>https://www.linkedin.com/in/marquita-priester-8b775217/</a> <br />"
    			+ "</p></div>"
    			+"<div class='col-md-12' style='padding: 1%;'><hr /></div></div>"
    			+"<div class='row' style='padding: 1%;'><div class='col-md-12'>"
    				+"<h3 style='padding-left: 2%; padding-right: 2%; padding-bottom: 1%; text-align: center;'>Summary of Qualifications</h3>"
	    			+"<p style='padding-left: 2%; padding-right: 2%; padding-bottom: 1%;'>Software development professional skilled in analysis and problem solving. Over 5 years of exclusive experience"
	    			+" in Java development, Spring Framework, and Hibernate. Gathered and refined requirements as a Business Analyst. "
	    			+"Performed unit testing, functional testing and QA testing. Over 5 years of experience with SQL development using "
	    			+"Oracle and SQL Server. Develops in Eclipse but experienced with Spring Tool Suite, Netbeans, IntelliJ and JDeveloper. "
	    			+"Worked with both waterfall and agile development paradigms. Utilizes critical thinking and problem solving skills "
	    			+"in execution of all tasks. Experienced with Git using Github, Stash, BitBucket and SVN using Tortoise SVN and "
	    			+"Eclipse Subversive Plugin. Able to obtain a Security Clearance.</p></div></div>"
	    		+"<div class='col-md-12' style='padding: 1%;'><hr /></div></div>"
    			+"<div class='row' style='padding: 1%;'><div class='col-md-12'>"
    			+"<h3 style='padding-left: 2%; padding-right: 2%; padding-bottom: 1%; text-align: center;'>Employment History</h3></div></div>"
    			+"<div class='row' style='padding-left: 3%; padding-right: 3%;'>"
    				+"<div class='col-md-6'><strong>Application Developer</strong><br />Collabera/Bank of America</div>"
    				+"<div class='col-md-6' style='text-align: right;'>February 2017 to present<br />Charlotte, NC</div>"
    			+"</div>"
    			+"<div class='row' style='padding-left: 3%; padding-right: 3%;'>"
    				+"<ul>"
    					+"<li>Performs QA testing, prepares the test case scripts and results, and presents the test case scripts to the team for review each sprint</li>"
    					+"<li>Implemented a data filter and search filter using jQuery to select the rows meeting the criteria dynamically</li>"
    					+"<li>Generated a query using a query builder via the builder design pattern that selects the rows that meet the user''s search criteria</li>"
    					+"<li>Implemented functionality upload contents of excel file to database</li>"
    					+"<li>Built content managing tool for Super User to add new links and update program status dynamically</li>"
    					+"<li>Serving as a Business Analyst for two applications by obtaining requirements for enhancements, conducting regular meetings with customers for briefing and explanation of efforts as well as demoing newly developed functionality</li>"
    					+"<li>Designed and implemented views using a variety of joins and select statements on SQL Server, created several database objects and performed many alter and update statements to modify tables for emerging needs and changes for applications</li>"
    					+"<li>Compiled extensive documentation of two programs maintained by the team</li>"
    				+"</ul>"
    			+"</div>"
    		+"<div class='row' style='padding-top: 2%; padding-left: 3%; padding-right: 3%;'>"
				+"<div class='col-md-6'><strong>Application Developer</strong><br />Collabera/Bank of America</div>"
				+"<div class='col-md-6' style='text-align: right;'>October 2015 to November 2016<br />Charlotte, NC</div>"
			+"</div>"
			+"<div class='row' style='padding-left: 3%; padding-right: 3%;'>"
				+"<ul>"
					+"<li>Served as a middle-tier and front-end developer for an internal Java web application using ThymeLeaf, CSS, HTML, SQL Server, jQuery, YUI, Java, Spring MVC Framework, and Selenium IDE on a team that practiced Agile Scrum</li>"
					+"<li>Enhanced the export view to organize templates by GCF and in descending order by rewriting the query, creating a tabbed view and tables containing the 5 most recent templates for each view. Implemented security to only allow use of a specific GCF to see their templates </li>"
					+"<li>Rewrote the User management module to save new users and edit existing users</li>"
					+"<li>Wrote the administrator view using Bootstrap and JQuery to use tree tabbed layout and tiles for each module</li>"
					+"<li>Developed a programmatic work flow that locked the generation of the JSON templates by checking if a template was being generated, whether a template had been generated in the last 30 days using jQuery and Java </li>"
					+"<li>Wrote unit tests using JUnit and Mockito for the application</li>"
					+"<li>Created a Selenium test suite for functional testing of a portlet application</li>"
				+"</ul>"
			+"</div>"
		+"<div class='row' style='padding-top: 2%; padding-left: 3%; padding-right: 3%;'>"
			+"<div class='col-md-6'><strong>Software Developer</strong><br />eScience & Technology Solutions, Inc.</div>"
			+"<div class='col-md-6' style='text-align: right;'>June 2014 to October 2015<br />North Charleston, SC</div>"
		+"</div>"
		+"<div class='row' style='padding-left: 3%; padding-right: 3%;'>"
			+"<ul>"
				+"<li>Served as a middle tier and front-end developer, with full stack support for a large web application being developed in the Liferay portal environment using JavaScript, Velocity Templates, CSS, HTML, Oracle, Java and Spring MVC Framework on a team that practiced Agile Scrum</li>"
				+"<li>Directed and mentored junior employees by providing guidance and assistance with development with either the UI or middle tier.</li>"
				+"<li>Deployed portlets and SQL scripts to remote Liferay instance and Oracle database for user testing</li>"
				+"<li>Developed and enhanced theme using Velocity Templates and CSS3, Font Awesome, Bootstrap, JavaScript/AJAX</li>"
				+"<li>Assisted in Java-based feature and portlet development and testing to include unit tests and integration testing</li>"
				+"<li>Used the Atlassian tool suite to manage deployments, story and bug tracking, and builds. Performed regular code reviews for peers and improved development skills and understanding through code reviews received.</li>"
			+"</ul>"
		+"</div>"
		+"<div class='row' style='padding-top: 2%; padding-left: 3%; padding-right: 3%;'>"
			+"<div class='col-md-6'><strong>Computer Scientist</strong><br />Department of the Navy, Space and Naval Warfare Systems Center, Atlantic</div>"
			+"<div class='col-md-6' style='text-align: right;'>August 2008 to May 2014<br />North Charleston, SC</div>"
		+"</div>"
		+"<div class='row' style='padding-left: 3%; padding-right: 3%;'>"
			+"<ul>"
				+"<li>Assisted with the creation of the Test Plan for the TFMMS project</li>"
				+"<li>Supported the Software Services IPT as a Java developer responsible for Spring MVC, Release 3.23 widget development with Maven in the Eclipse environment; uses Git repository for version control</li>"
				+"<li>Maintaining and implementing updates for applications developed with Java EE 1.5 and Oracle ADF in JDeveloper; uses SVN for version control</li>"
				+"<li>Worked on the migration of Oracle ADF applications to Liferay using Spring Portal MVC framework and Hibernate in the Eclipse environment as a Java Developer</li>"
				+"<li>Served as the Robotics STEM Outreach IPT Lead from 2013 to present; served as a mentor and volunteer at FIRST Lego League and FIRST Robotics Competition since 2010</li>"
				+"<li>Wrote and submitted two Innovation Proposals advocating robotic systems for first response and the use of LIDAR technology</li>"
				+"<li>Supported programs and projects that incorporated biometric capability, including providing technical knowledge and support for the development of an Automated Biometric Identification System as a Project Engineer</li>"
				+"<li>Gained Project Management experience as the PM for the Dept. of VA NCA Datacenter Get Well Program</li>"
				+"<li>Served as a Command recruiter and performed technical on-site interviews</li>"
			+"</ul>"
		+"</div>"
		+"<div class='col-md-12' style='padding: 1%;'><hr /></div></div>"
		+"<div class='row' style='padding: 1%;'><div class='col-md-12'>"
			+"<h3 style='padding-left: 2%; padding-right: 2%; padding-bottom: 1%; text-align: center;'>Education</h3></div></div>"
		+"<div class='row' style='padding-top: 2%; padding-left: 3%; padding-right: 3%;'>"
			+"<div class='col-md-6'><strong>Clark Atlanta University</strong>, Atlanta, GA<br />Accelerated BS/MS degree in Computer Science with Master's Thesis, May 2008</div>"
			+"<div class='col-md-6' style='text-align: right;'>Cumulative Undergraduate G.P.A.: 3.64<br />Cumulative Graduate G.P.A.: 3.90</div>"
		+"</div>"
		+"<div class='col-md-12' style='padding: 1%;'><hr /></div></div>"
		+"<div class='row' style='padding: 1%;'><div class='col-md-12'>"
		+"<h3 style='padding-left: 2%; padding-right: 2%; padding-bottom: 1%; text-align: center;'>Relevant Skills</h3></div></div>"
		+"<div class='row' style='padding: 1%; text-align: center;'><div class='col-md-1'>"
		+"Java"
		+"</div>"
		+"<div class='col-md-1'>"
		+"Spring MVC"
		+"</div>"
		+"<div class='col-md-1'>"
		+"Liferay"
		+"</div>"
		+"<div class='col-md-1'>"
		+"Eclipse"
		+"</div>"
		+"<div class='col-md-1'>"
		+"Hibernate"
		+"</div>"
		+"<div class='col-md-1'>"
		+"SQL"
		+"</div>"
		+"<div class='col-md-1'>"
		+"PHP"
		+"</div>"
		+"<div class='col-md-1'>"
		+"Oracle"
		+"</div>"
		+"<div class='col-md-1'>"
		+"HTML/CSS3"
		+"</div>"
		+"<div class='col-md-1'>"
		+"SQL Server"
		+"</div>"
		+"<div class='col-md-1'>"
		+"Selenium IDE"
		+"</div>"
		+"<div class='col-md-1'>"
		+"QA Testing"
		+"</div></div>"
		+"<div class='row' style='padding: 1%;'><div class='col-md-3' style='padding-left: 3%;'>"
		+"JavaScript/JQuery/AJAX"
		+"</div></div>"
		+"</div></body></html>";
        return content;
    }
}
